# Generated by Django 2.2.12 on 2020-05-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
    ]
